spring:
  application:
    name: UTILISATEUR-SERVICE # Nom unique du service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Adresse du serveur Eureka
  instance:
    prefer-ip-address: true # Utilise l'IP au lieu du nom d'h√¥te

